### PR TITLE
Allow Users add comments in Github.Party

### PR DESCRIPTION
**Pull request by tvvocold**
Like Yelp. ( Feel free to close this PR if you don't like it :)

### CODE REVIEW

**Comment by brendensoares** [comment]
@revel/core thoughts?

**Comment by brendensoares** [comment]
@tvvocold could you explain what we gain from this?

**Comment by pedromorgan** [comment]
I just looked at the site, and I cant figure out what its about... or am i missing something ?

**Comment by anonx** [comment]
@pedromorgan It looks like HN.

**Comment by tvvocold** [comment]
Well, You can check our [FAQ](https://github.party/item?id=5) and find some githubers [here](https://github.party/official). 
As you can see, G.P provide a HN-like comments platform for opensource project.

**Comment by pushrax** [comment]
:-1: there is no clear value that GH issues don't provide

**Comment by tvvocold** [comment]
@pushrax 
Well, i don't think use GH issue traker for user's comment is a better way.

`Issues are a great way to keep track of tasks, enhancements, and bugs for your projects.`
-https://guides.github.com/features/issues/

`Get/Post links/comments.`
-https://github.party/item?id=5

If you just don't like it (users comments/upvote), feel free to close this PR:)

**Comment by brendensoares** [comment]
@tvvocold thanks for the offer, but at this time we can't afford the resources to manage another protal for our project. Closing for now.

**Pull request closed without merging**
