### PR TITLE
 Fix change Server.Addr in the hook function and it does not work.

### PR DESCRIPTION
**Pull request by runner-mei**
Fix change Server.Addr in the hook function and it does not work.
Why change Server.Addr?
I hope read port from another config file, the config file is will modified by user and don't override while reinstall or update my software.

### CODE REVIEW

**Comment by runner-mei** [comment]
this is a pull request.

**Comment by brendensoares** [comment]
Looks like a harmless change, but what is the benefit?

**Comment by runner-mei** [comment]
My user change port of my app, but reinstall my app and will override config file, so I add hook to read port from the db.

**Comment by jeevatkm** [comment]
@runner-mei Thanks for your response.

**Pull request merged**
