### PR TITLE
Assets pipeline

### PR DESCRIPTION
**Pull request by huacnlee**
## Features

- Allow use [Assets Pipeline](http://guides.rubyonrails.org/asset_pipeline.html) to manage you JavaScript, CSS, or use CoffeeScript, SASS to write them like Rails.
- Serve assets on `/assets` path.
- Revel cmd will generate the assets templates in default.
- Add two default template helpers `javascript_include_tag`, `stylesheet_link_tag`
```
.
├── README.md
├── app
│   ├── assets
│   │   ├── images
│   │   │   ├── favicon.png
│   │   │   ├── glyphicons-halflings-white.png
│   │   │   └── glyphicons-halflings.png
│   │   ├── javascripts
│   │   │   ├── app.coffee
│   │   │   └── jquery-1.9.1.min.js
│   │   └── stylesheets
│   │       ├── app.scss
│   │       └── bootstrap.css
│   ├── controllers
```

```bash
$ curl http://127.0.0.1:9000/assets/stylesheets/app.css
source code from bootstrap.css
....
app.scss to css
```

## Requirements

- Ruby gems: sass, coffee-script

### CODE REVIEW

**Comment by brendensoares** [comment]
@huacnlee this is a great contribution!

Side point, we do need the PR to target `develop` instead of `master`. I can do this later since this feature is on our v0.13 roadmap.

I'll probably end up writing an RFC to spec out the details for how this will end up working, but this is a good foundation to build on.

**Comment by huacnlee** [comment]
Do you want me to create a PR to develop branch?

**Comment by brendensoares** [comment]
@huacnlee yes, please create a PR that targets the `develop` branch. Thanks!

**Comment by huacnlee** [comment]
#901

**Pull request closed without merging**
