### PR TITLE
PutForm test helper

### PR DESCRIPTION
**Pull request by grsmv**
Closing #895

### CODE REVIEW

**Comment by anonx** [comment]
@grsmv Thank you, LGTM :+1:. It will be merged to v0.13. Right, @brendensoares?

**Comment by brendensoares** [comment]
:+1: @anonx Yes sir, I'll add this to the roadmap as well.

**Comment by brendensoares** [comment]
@grsmv I edited the title as I think you meant `PutForm` not `PostForm`. Correct me if I'm wrong.

**Comment by anonx** [comment]
Thank you, @grsmv.

**Pull request merged**
