### PR TITLE
Allow binder to bind struct map, fixes #997

### LINKED ISSUE #997: Not able to bind struct map
consider the following struct

``` go
type TestStruct struct {
    SubStruct map[string]SubStruct
}
```

It seems not able to bind SubStruct automatically now. Is there any plan for this or any suggestion for this  situation?

### PR DESCRIPTION
**Pull request by wmh**
I modify bindMap a bit to allow binding struct map. Test cases are updated too. 
closes #997, #998

### CODE REVIEW

**Comment by pedromorgan** [comment]
Have u got a small example of this ?.. (thinking about the manual if this is merged)

**Comment by brendensoares** [comment]
A test use case would give me some good understanding into the intent of this change. Can you provide an example usage?

**Comment by runner-mei** [comment]
I like it, it is useful.

**Comment by pedromorgan** [comment]
Looks OK 2 md.. Merge it and we suffer...let's move on this is good

**Comment by wmh** [comment]
A test case already included in `binder_test.go`, is that enough as a simple example?

**Comment by notzippy** [comment]
@wmh Can you resolve your conflicts ?

**Comment by notzippy** [comment]
Replaced by #1208

**Pull request closed without merging**
