### PR TITLE
Map to index action of controllers when no action is specified.

### PR DESCRIPTION
**Pull request by carc1n0gen**
I figured other people would want the ability to route to index action of controller by default when none is provided.

### CODE REVIEW

**Comment by carc1n0gen** [comment]
Sorry meant to add a description.  I figured other people would want the ability to route to index action of controller by default when none is provided.

**Comment by anonx** [comment]
@carc1n0gen Will it show 404 or 500 if `index` method does not exist?

**Comment by carc1n0gen** [comment]
It displays 500 with the message "Template post/index.html not found."

**Comment by pushrax** [comment]
I don't think either of these are a good idea:

```
GET     /:controller/                           :controller.index
*       /:controller/:action                    :controller.:action
```

The potential security downside is pretty high.

**Comment by brendensoares** [comment]
I tend to agree with @pushrax on this issue. I don't much like catch all routes like this. I would remove the current catch all instead of adding another.

**Comment by brendensoares** [comment]
@carc1n0gen thanks for taking the time to share this with the community. I'm closing since it's an easy change for a dev to make themselves.

**Pull request closed without merging**
