### PR TITLE
ensure routes are loaded before returning from OnAppStart callback

### PR DESCRIPTION
**Pull request by pbnjay**
ensure routes are loaded before returning. #883

### CODE REVIEW

**Comment by brendensoares** [comment]
@pbnjay #855 has modified these lines. Could you review it and retest with the latest `develop`?

**Comment by pbnjay** [comment]
Doubt it. Routes still aren't loaded before returning in dev mode. Just need to pull the refresh above the its still, but can keep the err check.

**Comment by anonx** [comment]
@pbnjay I think @brendensoares asked whether you could update your PR because right now there is a merging conflict.

The change is something like this:
```diff
MainRouter = NewRouter(path.Join(BasePath, "conf", "routes"))
+err := MainRouter.Refresh()
if MainWatcher != nil && Config.BoolDefault("watch.routes", true) {
	MainWatcher.Listen(MainRouter, MainRouter.path)
-} else if err := MainRouter.Refresh(); err != nil {
+} else if err != nil {
	// Not in dev mode and Route loading failed, we should crash.
	ERROR.Panicln(err.Error())
}
```
or this:
```diff
MainRouter = NewRouter(path.Join(BasePath, "conf", "routes"))
+if err := MainRouter.Refresh(); err != nil {
+	// Not in dev mode and Route loading failed, we should crash.
+	ERROR.Panicln(err.Error())
+}
+
if MainWatcher != nil && Config.BoolDefault("watch.routes", true) {
	MainWatcher.Listen(MainRouter, MainRouter.path)
-} else if err := MainRouter.Refresh(); err != nil {
-	// Not in dev mode and Route loading failed, we should crash.
-	ERROR.Panicln(err.Error())
}
```
Right?

**Comment by pbnjay** [comment]
Yup. Was on my phone so couldn't make the update. Coming in shortly

**Pull request merged**
