### PR TITLE
Fix for issue #936 suggested by @anonx

### PR DESCRIPTION
**Pull request by bejayoharen**
Fix for issue #936 suggested by @anonx

### CODE REVIEW

**Comment by anonx** [comment]
My mistake, type cast of `int` to `time.Duration` is needed. Like:
```go
ReadTimeout:  time.Duration(Config.IntDefault("timeout.read", 0)) * time.Second
```

**Comment by anonx** [comment]
@bejayoharen And could you please target `develop` branch.

**Comment by bejayoharen** [comment]
Will do.

**Comment by anonx** [comment]
Resolved by #940.

**Comment by brendensoares** [comment]
:+1:

**Pull request closed without merging**
