### PR TITLE
Fix for issue #936 suggested by @anonx (#939)

### PR DESCRIPTION
**Pull request by bejayoharen**

### CODE REVIEW

**Comment by anonx** [comment]
Thank you, @bejayoharen. It has been merged into develop (see last two commits [here](https://github.com/revel/revel/commits/develop)).

@revel/core New behaviour is introduced by this PR. There are no timeouts by-default. However, if somebody needs them he/she can use `timeout.read` and `timeout.write` options in their `config/app.conf`. Example:
```ini
# Timeout specifies a time limit for request (in seconds) made by a single client.
# A Timeout of zero means no timeout.
timeout.read = 300
timeout.write = 60
```

**Comment by brendensoares** [comment]
@anonx would it be better to have the default be a sane value? No timeout seems dangerous for a default.

**Comment by bejayoharen** [comment]
I think 0 is the best default:

1. The timeouts are **very** unintuitive. For example, if you set the write timeout to 1 minute, then the server will timeout if it takes longer than one minute to *upload* a file. This is because, in the meantime, while uploading, nothing has been written to the socket, so it closes the connection.
2. Even large values could interfere with connections used for things like long-polling. (Why close a connect used for long-polling just because no data has gone through if you are still getting TCP keep-alives?) I think 0 is very sensible and sane for this use-case as well.

I think it's better to not use defaults and instead rely on lower-level TCP timeouts, file size limits and so on.

**Comment by brendensoares** [comment]
@bejayoharen time will tell what is the bet solution, but I feel if we make it clear that file uploads need a 0 timeout, then it wouldn't be bad to have safe defaults, like 60 seconds. Having no timeout makes a web app more vulnerable to DoS attacks, on purpose or on accident (high traffic spikes).

**Comment by anonx** [comment]
@brendensoares, Even if we decide to use some kind of default timeouts this PR is useful. It allows us to use `conf/app.conf.template` for that rather than hardcode something to `server.go`. So timeout values will be documented.

**Comment by bejayoharen** [comment]
@brendensoares For DoS, I would suggest adding the ability to set a minimum data rate, configure TCP timeouts, as well as the ability to limit request sizes (perhaps separate limits for both header and body), instead of socket read/write timeouts.

**Pull request closed without merging**
