### PR TITLE
support binary vendoring

### LINKED ISSUE #1092: revel build fails when vendoring revel binary
when I vendored revel binary and `github.com/revel/revel` in project `vendor` folder, `revel build` fails and output this error.

```
ERROR 2016/08/26 06:05:38 revel.go:317: Failed to find Revel with error: cannot find package "github.com/revel/revel" in any of:
        /usr/local/go/src/github.com/revel/revel (from $GOROOT)
        / ... /src/github.com/revel/revel (from $GOPATH)
```

This comes from calling build.Import with second arg being empty string.

### PR DESCRIPTION
**Pull request by Warashi**
this fix #1092

### CODE REVIEW

**Comment by Warashi** [comment]
sorry this fails other place

**Comment by pedromorgan** [comment]
Anyone tested this ?

**Comment by ottob** [comment]
I tested this today and have found two issues.

## 1. Modules doesn't work
I have this in my config `module.static=github.com/revel/modules/static`. When I start our revel app I get an error here https://github.com/revel/revel/blob/master/revel.go#L394 which makes sense, because there is no go code in the `static` folder root:
```
2017/06/12 23:57:09 revel.go:333: Failed to load module.  Import of github.com/revel/modules/static failed: cannot find package "github.com/revel/modules/static" in any of:
	/Users/ottob/go/src/mindoktor.io/mindoktor/CLINIC/vendor/github.com/revel/modules/static (vendor tree)
	/Users/ottob/go/src/mindoktor.io/mindoktor/vendor/github.com/revel/modules/static
	/usr/local/go/src/github.com/revel/modules/static (from $GOROOT)
	/Users/ottob/go/src/github.com/revel/modules/static (from $GOPATH)
```
I could hack around this by adding the following to the top of `addModule()` https://github.com/revel/revel/blob/master/revel.go#L401
```go
modulePath = strings.Replace(modulePath, "/app/controllers", "", 1)
```
and change  https://github.com/revel/revel/blob/master/revel.go#L394 to
```go
modPkg, err := build.Import(importPath+"/app/controllers", BasePath, build.FindOnly)
```
Then everything worked as expected.

## 2. vendor folder in parent folder of revel app doesn't work
We have our revel app in `$GOPATH/src/mindoktor.io/mindoktor/CLINIC` but our vendor folder is located in `$GOPATH/src/mindoktor.io/mindoktor/vendor/`, that is the parent folder of the revel app. This is valid in go and works with other go apps.

The check for the vendor path is too simple in `importPathFromPath()` defined here https://github.com/revel/cmd/blob/master/harness/reflect.go#L777. It expects the vendor folder to be in the revel app folder.

This might be an unusual setup so we can work around it by having a special vendor folder for our revel app. I just wanted to report it if it happens to be easy to fix.

**Comment by notzippy** [comment]
@ottob Just to clarify the issues you listed have to do with this PR and not with Revel as it is currently ?

**Comment by ottob** [comment]
Correct, when I use latest un-vendored `master` everything is working as expected.

**Comment by notzippy** [comment]
Closing since 1092 was closed

**Pull request closed without merging**
