### PR TITLE
UI and functional enhancements to the test runner page

### PR DESCRIPTION
**Pull request by eric-gilbertson**
enhanced-testrunner
   - more condensed layout to reduce need to scroll
   - move buttons to left so they are near the test name
   - add file level run, e.g. all tests in a given suite
   - remove table striping to better show test groups

## TODO
   - [ ] display tests in dir hierarchy, e.g. controller, service, model
   - [ ] add show/hide for each test dir
   - [ ] display sorted by name

### CODE REVIEW

**Comment by anonx** [comment]
Hi, @eric-gilbertson. I like your ideas: https://groups.google.com/forum/#!topic/revel-framework/mt__Z4w4a-E
Actually one of my early contributions to Revel was #725 and I was thinking about these things too. So, :+1: to your PR.

I prefer buttons at the right side though. I usually do not use mouse but when I do my cursor is at the right side of the screen most of the time. What are the preference of other users? I know `testrunner` is not likely the most popular part of Revel. But probably somebody will share with us their opinion regarding this aspect? @pedromorgan, @brendensoares, @notzippy 

P.S.: testrunner has been moved to a `modules` repo. Thus, you need to target it there: https://github.com/revel/modules/tree/develop

**Comment by pedromorgan** [comment]
- Buttons on the right side I would really like..
- Also a row hover, so I can see which line i'm on..

I also wouldnt mind the whole thing being more compact, with less spacing and smaller fonts, so i can get more on a page

just my thoughts

**Comment by eric-gilbertson** [comment]
As to button placement, one solution would be to place them on both the left and the right. I think it is good to have them on the left since it provides a tight visual coupling between then test name and the run button. Also, it accommodates those who work out of page left. 

Row hover tooltips could be added but given the use of bootstrap styling the rows cannot be shrunk much more as they already use the "xs" buttons.

If there is interest on this approach I will check it into the modules repo.

**Comment by anonx** [comment]
@eric-gilbertson What if test name would be a link for running tests. And we can make it `display: block` and `width: 100%`.

**Comment by eric-gilbertson** [comment]
I did try replacing the buttons with simple links and it does result in the saving of few more pixels per row. OTOH, I thought the presentation was less clear and that it was best to use a button because the click was invoking an action (as opposed to a view). Note that the condensed layout I checked in does already result in a vertical saving of approximately 30%. My $0.02 would be to keep the buttons for this iteration, but I can change back to links if that is the consensus. I would like to finish this issue so please let me know if you would like this change pushed to into modules and whether to use buttons or links. 

-Eric

**Comment by notzippy** [comment]
Another two cents.. If you hid the subtests for each controller you would save a lot more space, add a + beside the test button for the controller to display / hide the subtests.

**Comment by brendensoares** [comment]
@notzippy this is a good idea. Some more:
1. Show a live, [stacked](http://getbootstrap.com/components/#progress-stacked) [progress bar](http://foundation.zurb.com/docs/components/progress_bars.html)(linked to foundation framework because I like its markup better than bootstrap :)) of test results
2. Add animations to indicate status (e.g. blinking green when running)

**Comment by brendensoares** [comment]
@anonx why did we close this?

**Pull request closed without merging**
