### PR TITLE
support for . extension to return request.Format

### PR DESCRIPTION
**Pull request by u007**
based on rails concept, 
can we apply this?

### CODE REVIEW

**Comment by u007** [comment]
travis error?
github.com/bradfitz/gomemcache/memcache
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/asm.s:8 6a: No such file or directory: textflag.h
github.com/garyburd/redigo/internal
github.com/garyburd/redigo/redis
github.com/robfig/go-cache
The command "go get -v github.com/revel/revel/..." failed and exited with 2 during .
Your build has been stopped.

**Comment by pedromorgan** [comment]
Ok so this was one of wishes from before..

#963 and #659

**Comment by brendensoares** [comment]
#963 has a safer solution, though same end result.

**Comment by u007** [comment]
👍

**Pull request closed without merging**
