### PR TITLE
Adds first draft of a version file to Revel

### PR DESCRIPTION
**Pull request by brendensoares**
Parent: #418 

## TODO
- [x] add `version` file
- [x] add runtime parsing of version file and output to console

### CODE REVIEW

**Comment by pedromorgan** [comment]
Ok OK.. cool,, but now I realise a mistake, probably my fault..

Snag is that the remote "docs compiler" and jenkins etc,, need the actual source and name..

So what would work, after thinking about it..
```
name: "Revel Core" << name of package
source: github.com/revel/revel  <<  location
version: 0.1.2 << version no
date: 2015-12-24T11.59.59Z << date of version as panic release..
```

I know its just but more complicated.. but my python
fab get_revel failed.. as we need more meta..

Incidentally modules would be
```
name: "Auth Module" << name of package
source: github.com/revel/modules/foo  <<  location
version: 0.1.1 << version no
date: 2015-11-24T11.59.59Z << date of version as panic release..
```

anyway.. having it in Yaml is fantastic.. or in welsh 
```
"bendigedig" = rejoice and happy

ben di ge dig
head dizzy and high
```

**Comment by brendensoares** [comment]
I'd say this is now ready to merge. We can add a `revel version` command soon. @anonx @pushrax any feedback?

**Comment by brendensoares** [comment]
@revel/core I may be losing my mind, but is it even possible to consume the `version.yaml` file that we added? @pedromorgan is this consumed by the website or docs? Why did we add this? We should add a comment to this file as far as what it's purpose is.

**Comment by alkchr** [comment]
@brendensoares IIRC it is not consumed. We discussed it in IRC about a year ago. The plan was to start using it.

**Comment by pedromorgan** [comment]
The yaml is part of the documentation, and a way to determine what the "code is". Eg info on a new module or alike added to the documentation

**Comment by brendensoares** [comment]
@pedromorgan ok, could you provide more info for how we can make use of it? For example, the yaml file is not included in the `revel package` command, should it be?

**Pull request merged**
