### PR TITLE
Change compression handling

### PR DESCRIPTION
**Pull request by birkirb**
There are HTTP clients that go bananas when seeing a compression header on an empty response body.
In order to increase compatibility with these, I've made the compression conditional on the status code.

I'd like to add a test for this as well, but didn't see any 204, 304 in the fake apps. If you could give me some instructions I'd be happy to try and follow up on that.

### CODE REVIEW

**Comment by anonx** [comment]
> There are HTTP clients that go bananas when seeing a compression header on an empty response body.

@birkirb, what exactly do they do?

**Comment by birkirb** [comment]
In our case we had a problem with Samsung Galaxy Ace, running Android v2.3.6 (Gingerbread). Seems like their HTTP library would try to unzip a null (empty body) or something like that and throw an exception. I saw some anecdotal evidence suggesting it was also on issue on other systems but don't have any details.  

Since the body is already empty it seems like it shouldn't hurt to skip the compression.

**Comment by anonx** [comment]
@birkirb I wonder, wasn't it something related to this https://github.com/revel/revel/issues/733#issuecomment-56713379?

**Comment by birkirb** [comment]
Seems similar, although in that case it's that the controller action there is returning nil and not explicitly setting the content type etc. I've set the status and content type explicitly before returning in the cases where I use this.  HTTP standard stipulates there MUST not be a body on 204 and 304s, so again there is little point in trying to compress it.

**Comment by brendensoares** [comment]
@birkirb we can get this merged for v0.13, but first you need to target the `develop` branch.

**Comment by birkirb** [comment]
@brendensoares New request opened in #888, please close when ready.

**Pull request closed without merging**
