### PR TITLE
Request log

### PR DESCRIPTION
**Pull request by huacnlee**
```bash
Started GET /topics at 2015-03-28T18:09:41+08:00 from 127.0.0.1:57816
  [app.go:54] (0.72ms) SELECT  * FROM `users`  WHERE (`users`.deleted_at IS NULL OR `users`.deleted_at <= '0001-01-02') AND ((id = '13')) ORDER BY `users`.id ASC LIMIT 1
  [pagination.go:19] (0.59ms) SELECT  count(*) FROM `topics`  WHERE (`topics`.deleted_at IS NULL OR `topics`.deleted_at <= '0001-01-02') AND ((rank >= 0)) ORDER BY last_active_mark desc, id desc
  [topic.go:83] (1.97ms) SELECT  * FROM `topics`  WHERE (`topics`.deleted_at IS NULL OR `topics`.deleted_at <= '0001-01-02') AND ((rank >= 0)) ORDER BY last_active_mark desc, id desc LIMIT 20 OFFSET 0
  [topic.go:83] (0.82ms) SELECT  * FROM `users`  WHERE (`users`.deleted_at IS NULL OR `users`.deleted_at <= '0001-01-02') AND ((`id` in ('8','13','14')))
  [topic.go:83] (0.74ms) SELECT  * FROM `nodes`  WHERE (`nodes`.deleted_at IS NULL OR `nodes`.deleted_at <= '0001-01-02') AND ((`id` in ('2','0','9','12','10','11','15','1')))
  [ERROR]0 RenderArg names found for 1 extra RenderArgs
  [user.go:61] (0.57ms) SELECT  count(*) FROM `notifications`  WHERE (`user_id` = '13' and `read` = 0)
  [user.go:61] (0.60ms) SELECT  count(*) FROM `notifications`  WHERE (`user_id` = '13' and `read` = 0)
  [node.go:62] (0.58ms) SELECT  * FROM `node_groups`   ORDER BY sort desc
  [node.go:62] (1.34ms) SELECT  * FROM `nodes`  WHERE (`nodes`.deleted_at IS NULL OR `nodes`.deleted_at <= '0001-01-02') AND ((`node_group_id` IN ('1','2')))
Completed 200 in 18.32ms
```

## Changes:

1. Add instrument log for each request, include: `http status`, `request runtime`, `client ip`, `request time`,`path`,`http method`.
2. INFO logger use white color.
3. Update default log prefix for output tidy log.
4. Add SYSINFO logger.
5. Use WARN to print session warning message.

### CODE REVIEW

**Comment by brendensoares** [comment]
So, what is `SYSINFO` for?

**Comment by huacnlee** [comment]
Just want output a log without any indent. Before `INFO` is default set indent two space.

**Comment by brendensoares** [comment]
@huacnlee what about just making the log prefix values configurable via `app.conf` instead of adding an additional log level?

**Comment by huacnlee** [comment]
@brendensoares You means don't want add `SYSINFO`?

**Comment by anonx** [comment]
@brendensoares I think they are already configurable https://github.com/revel/revel/blob/master/skeleton/conf/app.conf.template#L82-L85

@huacnlee We have already had 4 loggers. It looks like that's enough for most cases. Otherwise, we would have to introduce `SYSERROR`, `SYSWARN`, `SYSTRACE`, too. And that's too much and not justified.

**Comment by huacnlee** [comment]
Old I just remove `SYSINFO`, And now default output like:

**Comment by brendensoares** [comment]
@anonx I see that the revel loggers get init'd and then replaced via `getLogger()` in `revel.go`.

@huacnlee are your log screenshots cropping out the log prefixes?

**Comment by huacnlee** [comment]
@brendensoares Yes, `INFO` have no prefixes.

**Comment by brendensoares** [comment]
@huacnlee so this PR just removes the "INFO" prefix? I'm not sure that is a good thing or not, but all of your other changes are good :+1: 

@anonx any comment on removing "INFO" prefix?

**Comment by huacnlee** [comment]
@brendensoares 

The important is add logs around the requests in `server.go`.
Remove `INFO` prefix it for output tidy format.

**Comment by brendensoares** [comment]
We'll get this in v0.13. Thanks @huacnlee!

**Comment by huacnlee** [comment]
:smile:

**Comment by alkchr** [comment]
Well... IMO the messages had to be `module` based ones, not built into the core.

**Pull request merged**
