### PR TITLE
Add latest improvements from original go-cache

### PR DESCRIPTION
**Pull request by brendensoares**
See revel/revel#983

~~Will push this PR through fast since it makes sense.~~

### CODE REVIEW

**Comment by brendensoares** [comment]
Oh dear, there seems to be an error:
```
# github.com/revel/revel/cache
cache/inmemory.go:48: undefined: cache.ErrKeyExists
cache/inmemory.go:62: c.Cache.cache.Delete(key) used as value
cache/inmemory.go:69: cannot use n (type uint64) as type int64 in argument to c.Cache.cache.Increment
cache/inmemory.go:69: assignment count mismatch: 2 = 1
cache/inmemory.go:70: undefined: cache.ErrCacheMiss
cache/inmemory.go:77: cannot use n (type uint64) as type int64 in argument to c.Cache.cache.Decrement
cache/inmemory.go:77: assignment count mismatch: 2 = 1
cache/inmemory.go:78: undefined: cache.ErrCacheMiss
```

Looks like a little more effort is needed. I can't look into it now, but if anyone else can, please chime in. I'll come back to this eventually, yet community support is welcome :dancer:

**Comment by DavidHunter** [comment]
Robfig modified the forked version https://github.com/robfig/go-cache/commit/9fc39e0dbf62c034ec4e45e6120fc69433a3ec51

**Comment by onlyjob** [comment]
Any progress please?

**Comment by brendensoares** [comment]
This has been deferred to the backlog @onlyjob due to incompatibilities.

### TODO
- [ ] compare performance benefits of original repo vs robfig's fork
- [ ] determine if it's worth forking the original repo into revel's GH org in order to apply [robfig's changes](https://github.com/robfig/go-cache/commit/9fc39e0dbf62c034ec4e45e6120fc69433a3ec51).

**Comment by notzippy** [comment]
Closing, was replaced by new PR

**Pull request closed without merging**
