### PR TITLE
#895 helpers for PUT methods in testing framework

### PR DESCRIPTION
**Pull request by grsmv**
Providing helpers for testing PUT requests with Revel testing framework

### CODE REVIEW

**Comment by anonx** [comment]
Hi, @grsmv. Thank you for your contribution. We have already had `PUT` method: https://github.com/revel/revel/blob/develop/testing/testsuite.go#L121

#781 is a related PR.

**Comment by grsmv** [comment]
Yep, definitely. But io.Reader is not actually better solution to imitate sending a form, so maybe we still need PutForm method?

**Comment by anonx** [comment]
@grsmv Oh, sorry, my mistake. You also added `PutForm`, I didn't notice that. Yeah, I think it's a valuable thing which is worth being merged. But you will have to target the `develop` branch per [Revel's Contributing Guidelines](https://github.com/revel/revel/blob/master/CONTRIBUTING.md#how-revel-is-developed).

**Comment by grsmv** [comment]
Thank you. I'll close this and reopen #897

**Comment by brendensoares** [comment]
:+1:

**Pull request closed without merging**
