### PR TITLE
Session engine support.

### PR DESCRIPTION
**Pull request by notzippy**
Configurable session engine, register interface revel.SessionRegisterSessionEngine(f func() revel.SessionEngine, name string)
Session engine is chosen from app.conf value session.engine
Currently only engine type is revel-cookie.
Adds the feature to store interface{} session from controller using SessionMarshal, SessionUnmarshal, SessionDelete methods.

### CODE REVIEW

**Comment by notzippy** [comment]
I am not really sure this will work in all situations

**Comment by pedromorgan** [comment]
Look good to me, I;m already serialising json, so this solves my problem..

**Comment by notzippy** [comment]
@pedromorgan 
I am torn if I should be adding two new methods (and two maps) on the controller to do this. Or if this should be implemented elsewhere and injected onto the controller as a single object - my other thoughts are on `page session` data (data that would be persisted through a series of JSON requests, ie only be relevant for that page)

**Comment by notzippy** [comment]
I am testing a new approach where the c.Session object is changed to a `map[string]interface{}` Since this is a breaking change I am deferring this PR till next release...

**Pull request merged**
