### PR TITLE
[RETARGET] support pprof/trace

### PR DESCRIPTION
**Pull request by tw4452852**
support runtime tracing

### CODE REVIEW

**Comment by pushrax** [comment]
Looks good, though can you target the `develop` branch as described in the [CONTRIBUTING.md](https://github.com/revel/revel/blob/master/CONTRIBUTING.md)?

**Comment by tw4452852** [comment]
@brendensoares Done. #874

**Comment by tw4452852** [comment]
@pushrax @brendensoares Done. #874

**Comment by brendensoares** [comment]
:+1:

**Pull request closed without merging**
