### PR TITLE
add 1.7 and 1.8 to testing

### PR DESCRIPTION
**Pull request by shawncatz**
also, trying to figure out the problems with testing in travis

### CODE REVIEW

**Comment by notzippy** [comment]
@shawncatz can you add `- redis-cli info` to the before_install section  ? like

    before_install:
      - redis-cli info

**Comment by shawncatz** [comment]
yep. added the redis-cli info command

**Comment by notzippy** [comment]
Can you modify your pr and update the one line from ` if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install memcached redis fi` to ` if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install memcached redis && brew services start redis; fi`

**Comment by notzippy** [comment]
Finally working @shawncatz

**Comment by shawncatz** [comment]
This removed 1.4 from the testing matrix, and that wasn't really discussed with anyone (I removed it just to create a change to force a build, I had intended on putting it back)... @brendensoares we should discuss which versions of go we want to support going forward

**Pull request merged**
