### PR TITLE
changed default CookieSecure to false

### PR DESCRIPTION
**Pull request by lujiacn**
to make session work in prod mode at least.

### CODE REVIEW

**Comment by lujiacn** [comment]
not sure how to use secure attribute in http.Cookie, but from the example below, for http request, if set secure as true, no cookie set.
So, if do not set CookieSecure, default value is false, not !DevMode, works for http. If set https, may be use CookieSecure "true"
```
package main

import (
        "fmt"
        "net/http"
        "time"
)

func answer(w http.ResponseWriter, r *http.Request) {
        cookie := http.Cookie{Name: "locality", Value: "here",
                Expires:  time.Now().Add(time.Hour),
                HttpOnly: true, MaxAge: 50000,
                Path: "/", Secure: true}
        http.SetCookie(w, &cookie)
        fmt.Fprintf(w, "Yay")
        cooki, err := r.Cookie("locality")
        fmt.Fprint(w, cooki, err)
        //http.Redirect(w, r, "/", http.StatusFound)
}

func main() {
        http.HandleFunc("/", answer)
        err := http.ListenAndServe(":8888", nil)
        if err != nil {
                fmt.Println(err)
        }
}
```

**Comment by notzippy** [comment]
Reference #1097

**Comment by brendensoares** [comment]
@lujiacn we discussed this issue as a team and decided the best solution is to change the default value to be based on the availability of HTTPS that way we avoid any negative side effects with Sessions not working.

The following change should do it:
`CookieSecure = Config.BoolDefault("cookie.secure", HttpSsl)`

Are you able to make this change or should we take control of this PR?

**Comment by shawncatz** [comment]
didn't hear back from original contributor, closing in favor of #1141

**Pull request closed without merging**
