### PR TITLE
Minor fixes to the contribution guide

### PR DESCRIPTION
**Pull request by funyug**
Updated Command:
`git checkout -b feature/useful-new-thing origin/develop`
Current command : 
`git checkout -b feature/useful-new-thing develop`
Problem:
This tries to find the local branch develop which instead should use the remote branch origin/develop.

Updated Command:
`git push fork feature/useful-new-thing`
Current command:
`git push fork develop`
Problem:
This tries to push the changes to the branch develop instead of the feature branch.

### CODE REVIEW

**Comment by notzippy** [comment]
Do you think this should be kept in this format, or should we reformat it like this : https://github.com/revel/revel/wiki/Creating-a-Development-Environment

**Comment by shawncatz** [comment]
I think there's a larger project to go through and normalize all of the docs, but for v0.14 we can just push this out

**Comment by pedromorgan** [comment]
Its on the TODO list to explain how to fork/branch in revel, in the manual probably on the qucikref page,

http://revel.github.io/quickref/index.html

**Comment by shawncatz** [comment]
close/reopen to force new build

**Pull request merged**
