### PR TITLE
Added a client ip into controller instance

### PR DESCRIPTION
**Pull request by jeevatkm**
Implementation for #1068

### CODE REVIEW

**Comment by brendensoares** [comment]
We should consider the field name. Revel was inspired from the Rails and Play web frameworks. We can also consider the naming in other popular web frameworks like Node.JS and PHP:

- `request.ip` and `request.remote_ip` [Ruby on Rails](https://stackoverflow.com/questions/10997005/whats-the-difference-between-request-remote-ip-and-request-ip-in-rails)
- `request().remoteAddress()` [Java Play](https://stackoverflow.com/questions/11721215/how-to-get-ip-address-of-the-client-in-play-framework-2-0)
- `request.connection.remoteAddress` [Node.JS](https://stackoverflow.com/questions/8107856/how-to-determine-a-users-ip-address-in-node)
- `Request::$client_ip` and `@_SERVER['REMOTE_ADDR']` [Kohana PHP](https://stackoverflow.com/questions/11565190/kohana-accessing-client-ip)

Does anyone have any preference? I feel there is value in choosing a naming convention that will be familiar to developers who have used other web frameworks.

**Comment by jeevatkm** [comment]
I have read your inputs, below is equivalent to Go `http.Request.RemoteAddr` and it's language level-
- `request().remoteAddress()` [Java Play](https://stackoverflow.com/questions/11721215/how-to-get-ip-address-of-the-client-in-play-framework-2-0)
- `request.connection.remoteAddress` [Node.JS](https://stackoverflow.com/questions/8107856/how-to-determine-a-users-ip-address-in-node)
`@_SERVER['REMOTE_ADDR']` [Kohana PHP](https://stackoverflow.com/questions/11565190/kohana-accessing-client-ip)

Below one, customized by respective framework-
- `request.ip` and `request.remote_ip` [Ruby on Rails](https://stackoverflow.com/questions/10997005/whats-the-difference-between-request-remote-ip-and-request-ip-in-rails)
- `Request::$client_ip` [Kohana PHP](https://stackoverflow.com/questions/11565190/kohana-accessing-client-ip)

Now, let's come to Revel. It can provide -
- `ServerIP` - comes from `app.conf - http.addr` or local `loopback` address
  - Or We call this as `IP` and add documentation explaining this is server ip. Like Ruby SO question
- `ClientIP` or `RemoteIP` in the Controller
  - Both terms is know in the industry and developers familiar to it

**Comment by jeevatkm** [comment]
@brendensoares what is the final take on this?

**Comment by brendensoares** [comment]
Thanks for taking the time to consider our options on this. Let's merge this!

**Comment by brendensoares** [comment]
PS - what can we do to document this new API addition?

**Comment by jeevatkm** [comment]
`ClientIP` method already has godoc, all we need to do is updating controller attributes in the manual.

**Pull request merged**
